service: infra-23
frameworkVersion: '3'
configValidationMode: error
provider:
  name: aws
  deploymentMethod: direct
  region: us-east-2
  deploymentPrefix: infra-23

resources:
  - ${file(./resources/ecr.yml)}
  - ${file(./resources/ssmparameters.yml)}